# Generated by Django 2.2.10 on 2020-02-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200228_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='slug',
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.IntegerField(choices=[(1, 'Высокий приоритет'), (2, 'Средний приоритет'), (3, 'Низкий приоритет')], default=2, verbose_name='Приоритет'),
        ),
    ]
