# Generated by Django 2.2.10 on 2020-02-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200228_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(unique=True, verbose_name='описание'),
        ),
    ]
